// src/lib/products.ts

import { Product, Category } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "c1", name: "Electronics", slug: "electronics" },
  { id: "c2", name: "Fashion", slug: "fashion" },
  { id: "c3", name: "Home", slug: "home" },
];

export const PRODUCTS: Product[] = [
  // --- ELECTRONICS ---
  {
    id: "e1",
    name: "ProBook X15 Laptop",
    price: 1299.99,
    description: "Ultra-slim 15-inch laptop with a powerful M-series processor, 16GB RAM, and all-day battery life. Perfect for professionals and creators.",
    category: "Electronics",
    image: "https://picsum.photos/seed/e1/400/300",
    rating: 4.8,
    stock: 45,
    tags: ["laptop", "computer", "tech", "work"],
  },
  {
    id: "e2",
    name: "Noise-Cancelling Headphones",
    price: 249.50,
    description: "Premium over-ear headphones with active noise cancellation, deep bass, and 30 hours of playtime.",
    category: "Electronics",
    image: "https://picsum.photos/seed/e2/400/300",
    rating: 4.6,
    stock: 120,
    tags: ["audio", "music", "wireless"],
  },
  {
    id: "e3",
    name: "Vanguard Smartwatch",
    price: 199.00,
    description: "Track your fitness, receive notifications, and monitor your heart rate with this sleek, water-resistant smartwatch.",
    category: "Electronics",
    image: "https://picsum.photos/seed/e3/400/300",
    rating: 4.3,
    stock: 85,
    tags: ["wearable", "fitness", "watch"],
  },
  {
    id: "e4",
    name: "Mirrorless Digital Camera",
    price: 899.00,
    description: "Capture stunning 4K video and high-resolution photos. Includes a versatile 18-55mm kit lens.",
    category: "Electronics",
    image: "https://picsum.photos/seed/e4/400/300",
    rating: 4.9,
    stock: 12,
    tags: ["photography", "camera", "video"],
  },

  // --- FASHION ---
  {
    id: "f1",
    name: "Classic Denim Jacket",
    price: 89.99,
    description: "A timeless vintage-wash denim jacket. Durable, comfortable, and pairs perfectly with almost any outfit.",
    category: "Fashion",
    image: "https://picsum.photos/seed/f1/400/300",
    rating: 4.5,
    stock: 60,
    tags: ["clothing", "jacket", "denim", "unisex"],
  },
  {
    id: "f2",
    name: "Urban Runner Sneakers",
    price: 120.00,
    description: "Lightweight, breathable mesh sneakers designed for both city commutes and intense gym sessions.",
    category: "Fashion",
    image: "https://picsum.photos/seed/f2/400/300",
    rating: 4.7,
    stock: 34,
    tags: ["shoes", "footwear", "athletic"],
  },
  {
    id: "f3",
    name: "Polarized Aviator Sunglasses",
    price: 55.00,
    description: "Stylish metal-frame aviators with UV400 polarized lenses to protect your eyes from harsh glare.",
    category: "Fashion",
    image: "https://picsum.photos/seed/f3/400/300",
    rating: 4.2,
    stock: 200,
    tags: ["accessories", "eyewear", "summer"],
  },
  {
    id: "f4",
    name: "Leather Weekend Duffel",
    price: 150.00,
    description: "Spacious genuine leather duffel bag, perfect for short trips and weekend getaways.",
    category: "Fashion",
    image: "https://picsum.photos/seed/f4/400/300",
    rating: 4.8,
    stock: 25,
    tags: ["bags", "travel", "leather"],
  },

  // --- HOME ---
  {
    id: "h1",
    name: "Artisan Espresso Machine",
    price: 350.00,
    description: "Brew barista-quality espresso at home. Features a built-in milk frother and precise temperature control.",
    category: "Home",
    image: "https://picsum.photos/seed/h1/400/300",
    rating: 4.6,
    stock: 18,
    tags: ["kitchen", "coffee", "appliance"],
  },
  {
    id: "h2",
    name: "Minimalist Desk Lamp",
    price: 45.00,
    description: "Sleek LED desk lamp with adjustable brightness levels and color temperatures. Includes a built-in wireless phone charger.",
    category: "Home",
    image: "https://picsum.photos/seed/h2/400/300",
    rating: 4.4,
    stock: 75,
    tags: ["lighting", "office", "decor"],
  },
  {
    id: "h3",
    name: "Chunky Knit Throw Blanket",
    price: 65.00,
    description: "Incredibly soft and warm hand-knitted throw blanket. Adds a cozy, rustic touch to any living room or bedroom.",
    category: "Home",
    image: "https://picsum.photos/seed/h3/400/300",
    rating: 4.9,
    stock: 110,
    tags: ["bedding", "cozy", "decor"],
  },
  {
    id: "h4",
    name: "Ceramic Indoor Planter",
    price: 32.50,
    description: "Modern matte ceramic planter with a drainage hole and matching saucer. Perfect for medium-sized house plants.",
    category: "Home",
    image: "https://picsum.photos/seed/h4/400/300",
    rating: 4.1,
    stock: 90,
    tags: ["garden", "plants", "decor"],
  },
];